
```{r, warning=FALSE}
library(ggplot2)
library(dplyr)
```


```{r}
meat_supply <- read.csv("data/meat-supply-per-person.csv", check.names = FALSE)
gdp_data <- read.csv("data/gdp-per-person.csv")
population <- read.csv("data/population-by-country.csv")
population_age <- read.csv("data/median-age-country.csv", check.names = FALSE)
religion_data <- read.csv("data/religion-by-country.csv")
urban_pop <- read.csv("data/urban-population.csv",sep = ",",check.names = FALSE, encoding ="UTF-8")
beef_data <- read.csv("data/beef_production.csv",sep = ",",check.names = FALSE, encoding ="UTF-8")
meat_production_data <- read.csv("data/meat-production-tonnes.csv",sep = ",",check.names = FALSE, encoding ="UTF-8")
idh_data <- read.csv("data/idh_world.csv",sep = ",",check.names = FALSE, encoding ="UTF-8")
```


```{r}
colnames(beef_data)[4] <- "beef_production"
colnames(beef_data)[1] <- "Pais"
colnames(meat_production_data)[4] <- "meat_production_tonnes"
colnames(meat_production_data)[1] <- "Pais"
```

```{r}
beef_production_2018 <- beef_data %>% filter(Year==2018) %>% select(Pais, beef_production)
meat_production_2018 <- meat_production_data %>% filter(Year==2018) %>% select(Pais, meat_production_tonnes)
```

```{r}
#Del dataset population seleccionamos sólo la poblacion 2020
colnames(meat_supply)[4] <- "Meat_kg_yr"
meat_supply_per_capita <- meat_supply %>% select(Entity, Year, Meat_kg_yr) %>% filter(Year == 2017)
meat_supply_per_capita <- subset(meat_supply_per_capita, select = -Year)
colnames(meat_supply_per_capita)[2] <- "Meat_kg_2017"
colnames(meat_supply_per_capita)[1] <- "Pais"

gdp <- gdp_data %>% select(country, gdpPerCapita, pop)
colnames(gdp)[1] <- "Pais"

colnames(population_age)[1] <- "Pais"
population_age$pop2020 <- as.integer(population_age$pop2020*1000)
pop_age <- population_age %>% select(Pais, pop2020, MedianAge)

pop <- population %>% select(name,pop2020)
colnames(pop)[1] <- "Pais"
colnames(urban_pop)[1] <- "Pais"
urban_2018 <- urban_pop %>% select(Pais,"2018")
colnames(urban_2018)[2] <- "urb2018"

colnames(religion_data)[1] <- "Pais"

#Arreglo del IDH
colnames(idh_data)[2] <- "Pais"

#Ordenamos los datos de idh y seleccionamos sólo las columnas que nos aportan información sobre cada país
idh_data <- idh_data[order(idh_data$`HDI Rank (2018)`),][24:nrow(idh_data),]
#Filtramos el IDH sólo para el año 2018
idh <- idh_data %>% select(Pais, "2018")
idh$`2018` <- as.numeric(as.character(idh_data$`2018`))
idh <- idh[order(idh$`2018`,decreasing = TRUE),]
idh$division_idh <- cut(idh$`2018`, breaks=c(0,0.549,0.700, 0.801, 1), labels=c("bajo","medio","alto","muy_alto"))
colnames(idh)[2] <- "idh_2018"

```


```{r}
data_1 <- merge(pop_age, meat_supply_per_capita, by = "Pais", all.x = TRUE)
data_2 <- merge(data_1, meat_production_2018, by = "Pais", all.x = TRUE)
data_3 <- merge(data_2, urban_2018, by = "Pais", all.x = TRUE)
data_4 <- merge(data_3, select(gdp,Pais,gdpPerCapita), by = "Pais", all.x = TRUE)
data_5 <- merge(data_4, idh, by = "Pais", all.x = TRUE)
data <- merge(data_5, select(religion_data,Pais,chistians,unaffiliated,hindus), by = "Pais", all.x = TRUE)
#data$meat_production_per_capita <- data$meat_production_tonnes/data$pop2020
#data$unaffiliated_100 <- data$unaffiliated/data$pop2020*100000
data <- na.omit(data)
#Creacion hindues,cristianos cada 100k habitantes
data$chistians_100 <- (data$chistians/data$pop2020)*100000
data$unaffiliated_100 <- (data$unaffiliated/data$pop2020)*100000
data$hindus_100 <- (data$hindus/data$pop2020)*100000

```


*EDA:*

```{r}
g3 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(hindus_100), colour = division_idh)) + 
  geom_point(size = 5) + 
  labs(title="log Producción de carne vs log Hindús cada 100.000 habitantes", y = "log producción de carne", x="log Hindues cada 100.000 hab.")+ theme_bw()

ggsave(plot = g3, dpi = 300,width = 10, height = 6, filename = "meat_production_vs_hindus_100_idh.pdf")
```

```{r}

g0 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(hindus_100))) + 
  geom_point(size = 4, color="red") + 
  labs(title="log Producción de carne vs log Hindús cada 100.000 habitantes", y = "log producción de carne", x="log Hindues cada 100.000 hab.")+ theme_bw() + scale_colour_manual(values=c("black","red"))
g0
ggsave(plot = g0, dpi = 300,width = 10, height = 6, filename = "meat_production_vs_hindus_100.pdf")

```

```{r}
data$p_hindues <- (data$hindus/data$pop2020)*100
data$Proporción <- ifelse(data$p_hindues>10.0,">10% Hindú","<10% Hindú")
```

```{r}
g1 <- data %>% filter(p_hindues>10.0) %>% ggplot(aes(x=Pais,y=log(meat_production_tonnes))) + geom_bar(stat="identity",fill="brown") + coord_flip() + theme_bw() + labs(title="Paises que tienen mas un 10% de población Hindú")
g1
ggsave(plot = g1, width = 10, height = 10, dpi = 300, filename = "pais_vs_hindus_100.pdf")
```

```{r}
g2 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(hindus_100), colour = Proporción)) + 
  geom_point(size = 4) + 
  labs(title="log Producción de carne vs log Hindús cada 100.000 habitantes", y = "log producción de carne", x="log Hindues cada 100.000 hab.")+ theme_bw() + scale_colour_manual(values=c("black","red"))
g2
ggsave(plot = g2, dpi = 300,width = 10, height = 6, filename = "meat_production_vs_hindus_100_p.pdf")
```
```{r}
g4 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(Meat_kg_2017), colour = Proporción)) + 
  geom_point(size = 5) + 
  labs(title="log Producción de carne vs log Consumo de carne per cápita", y = "log producción de carne", x="log Consumo de carne per cápita")+ theme_bw() + scale_colour_manual(values=c("black","red"))+
   geom_text(aes(label=ifelse(p_hindues>=10.0,as.character(Pais),'')),hjust=-0.2, vjust=0.5)
g4
ggsave(plot = g4, dpi = 300, width = 10, height = 6, filename = "meat_production_vs_meat_consumo_per_capita.pdf")
```

```{r}
g5 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(hindus_100), colour = Proporción)) + 
  geom_point(size = 4) + 
  labs(title="log Producción de carne vs log Hindús cada 100.000 habitantes", y = "log producción de carne", x="log Hindues cada 100.000 hab.")+ theme_bw() + scale_colour_manual(values=c("black","red"))
g5
ggsave(plot = g5, dpi = 300, width = 10, height = 6, filename = "meat_vs_hindus.pdf")
```

```{r}
g6 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = gdpPerCapita, colour = Proporción)) + 
  geom_point(size = 2) + 
  labs(title="log Producción de carne vs PIB per cápita", y = "log producción de carne", x="PIB per cápita")+ theme_bw() + scale_colour_manual(values=c("black","red"))+
   geom_text(aes(label=ifelse(p_hindues>=10.0,as.character(Pais),'')),hjust=-0.5, vjust=0.5)
g6
ggsave(plot = g6, dpi = 300, width = 10, height = 6, filename = "meat_production_vs_PIB.pdf")
```

```{r}
data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(hindus_100), colour = division_idh)) + 
  geom_point(size = 2) + 
  labs(title="log Producción de carne vs log Hindús cada 100.000 habitantes", y = "log producción de carne", x="log Hindues cada 100.000 hab.")+ theme_bw()

```

```{r}
g7 <- data %>% ggplot(aes(y = log(meat_production_tonnes) , x = log(pop2020), colour = Proporción)) + 
  geom_point(size=4) + 
  labs(title="log Producción de carne vs log Población", y = "log Producción de carne[toneladas]", x="log Población") + 
  theme_bw() +
  scale_color_manual(values=c("black","red"))
g7
ggsave(plot = g7, dpi = 300, width = 10, height = 6, filename = "meat_production_vs_pob_p.pdf")
```

```{r}
p3 <- data %>% ggplot(aes(x = log(meat_production_tonnes) , y = MedianAge, colour = division_idh )) + 
  geom_point(size=4) + 
  labs(title="log producción de carne vs Edad media población", x = "log producción de carne", y="Edad media población")+ 
  theme_bw()
p3
```
```{r}
p4 <- data %>% ggplot(aes(x = log(meat_production_tonnes) , y = urb2018, colour = Proporción)) + 
  geom_point(size=4) + 
  labs(title="log Producción de carne vs % Urbanización", x = "log producción de carne", y="% Urbanización") + 
  theme_bw()
p4
```
```{r}
data$meat_production_per_capita <- data$meat_production_tonnes/data$pop2020
g6 <- data %>% ggplot(aes(x = log(meat_production_per_capita), y = log(gdpPerCapita), colour = Proporción)) + 
  geom_point(size=4) + 
  labs(title="log Producción de carne per cápita vs log PIB per cápita", x = "log Producción de carne per cápita", y="log PIB per cápita") + 
  theme_bw() +
  scale_color_manual(values=c("black","red"))
g6
ggsave(plot = g6, dpi = 300, width = 10, height = 6, filename = "meat_production_per_capita_vs_PIB.pdf")
```
```{r}
#data %>% ggplot(aes(x = division_idh, y = log(Meat_kg_2017))) + geom_boxplot() + theme_bw()
data %>% ggplot(aes(x = Proporción, y = log(Meat_kg_2017))) + geom_boxplot() + theme_bw()
```

```{r,fig.width=6, fig.height=25,}
#ggplot(na.omit(data), aes(x = Meat_kg_2017 , y = reorder(Pais, Meat_kg_2017))) + 
#  geom_bar(stat = "identity") + 
#  labs(title="Pais vs consumo de carne per cápita al año 2017", x = "Consumo de carne per cápita al año 2017", y="País") + 
#  theme_bw()  
  #+coord_cartesian(xlim = c(0, 100), ylim = c(10, 20))

```

```{r,fig.width=6, fig.height=4,}
ggplot(data, aes(x = Proporción , y = log(meat_production_tonnes) )) + 
  geom_boxplot() + 
  labs(title="Boxplot división IDH", x = "División IDH", y="Producción de carne[toneladas]") + 
  theme_bw()  
  #+coord_cartesian(xlim = c(0, 100), ylim = c(10, 20))

```

```{r}
str(data)
```

```{r}
library(corrplot)
correlacion <- cor(data[,c(2,3,4,5,6,7,8,15)])
round(correlacion, digits = 2)
corrplot(correlacion, method = "shade", shade.col = NA, tl.col = "black", tl.srt = 70, addCoef.col = "black")
```

*REGRESIONES*
```{r}
library(stargazer)
model_1 <- lm(log(meat_production_tonnes)~log(hindus_100) ,data=data)
model_2 <- lm(log(meat_production_tonnes)~log(hindus_100)+Proporción ,data=data)
model_3 <- lm(log(meat_production_tonnes)~log(hindus_100)+Proporción+idh_2018 ,data=data)
model_4 <- lm(log(meat_production_tonnes)~log(hindus_100)+Proporción+idh_2018+idh_2018*Proporción,data=data)
#model_4 <- lm(log(meat_production_tonnes)~log(hindus_100)+Proporción+log(gdpPerCapita) ,data=data)
stargazer(model_1,model_2,model_3,model_4, type="latex", align = TRUE, dep.var.labels = c("log(Producción de carne anual)"),covariate.labels=c("log(Hindúes100)","PHindú>10","IDH","IDH*PHindú>10"),no.space=TRUE, omit.stat = c("f","ser"), title="Modelos", out="modelo_gpd.htm")
#summary(model_2)
#stargazer(attitude)
```

